homme(albert).
homme(jean).
homme(paul).
homme(bertrand).
homme(louis).
homme(benoit).
femme(germaine).
femme(christiane).
femme(simone).
femme(marie).
femme(sophie).
pere(albert,jean).
pere(jean,paul).
pere(paul,bertran).
pere(paul,sophie).
pere(jean,simone).
pere(louis,benoit).
mere(germaine,jean).
mere(christiane,simone).
mere(christiane,paul).
mere(simone,benoit).
mere(marie,bertrand).
mere(marie,sophie).
parent(X,Y):-pere(X,Y);mere(X,Y).
fils(X,Y):-parent(Y,X),homme(X).
fille(X,Y):-parent(Y,X),femme(X).
grand_pere(X,Y):-parent(X,Z),parent(Z,Y),homme(X).
grand_pere(X,Y):-parent(X,Z),parent(Z,Y),femme(X).
frere(X,Y):-parent(Z,X),parent(Z,Y);mere(Z,X),mere(Z,Y);pere(Z,X),pere(Z,Y),homme(X),X\==Y.
soeur(X,Y):-parent(Z,X),parent(Z,Y);mere(Z,X),mere(Z,Y);pere(Z,X),pere(Z,Y),femme(X),X\==Y.
